general:
  kafka-topic: "my-topic"

  kafka:
    topic:
      name: midas-transactions

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: midas-core-group
      auto-offset-reset: earliest
